In [3]:
import numpy as np

In [4]:
import time

http://www.scipy-lectures.org/index.html

---

Core numeric libraries

Numpy: numerical computing with powerful numerical arrays objects, and routines to manipulate them. http://www.numpy.org/

See also chapter on numpy
Scipy : high-level numerical routines. Optimization, regression, interpolation, etc http://www.scipy.org/

See also chapter on scipy
Matplotlib : 2-D visualization, “publication-ready” plots http://matplotlib.org/

See also chapter on matplotlib

---

numpy pdf참고

In [5]:
np.__version__ #항상체크

'1.16.2'

In [6]:
a = np.array([1,2,3,4,'5',6])

In [7]:
a #호모지니어스

array(['1', '2', '3', '4', '5', '6'], dtype='<U11')

In [8]:
a = np.array([1,2,3,4,5,6])

In [9]:
a

array([1, 2, 3, 4, 5, 6])

In [10]:
b = [1,2,3,4,5,6]

In [11]:
b + 3

TypeError: can only concatenate list (not "int") to list

In [12]:
a + 3 #각각 3을 더해준다.

array([4, 5, 6, 7, 8, 9])

In [13]:
a.dot(a) # 외적,내적함수를 쉽게 구할수있다.

91

In [14]:
np.sum(a)

21

In [15]:
a = [[1,2],[3,4]]

In [16]:
sum(a)

TypeError: unsupported operand type(s) for +: 'int' and 'list'

In [17]:
np.sum(a)

10

In [18]:
np.sum(a,axis = 1) #행만 더해준다.

array([3, 7])

In [19]:
np.sum(a,axis = 0) #열로만 더해준다.

array([4, 6])

In [20]:
a = np.arange(10) 

In [21]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
%timeit np.sum(np.arange(10000))

In [ ]:
%timeit sum(range(100000))

In [22]:
type(a)

numpy.ndarray

In [23]:
dir(a)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__

In [25]:
a = [[1,2],[3,4]]

In [26]:
c = np.array(a)

In [27]:
c.dtype

dtype('int32')

In [29]:
c.size #원소의 개수

4

In [34]:
c.shape #2행 2열로 만들어져 있다. shape으로 size를 알수있다.

(2, 2)

In [35]:
c.ndim #2차원이다.

2

shape,ndim 으로 확인

In [37]:
c[0][1]

2

In [39]:
c[0,1] #이런식도 지원해준다.

2

In [40]:
c[0]

array([1, 2])

In [45]:
x = np.ones((5,4)) #ones는 싹다 1로 채워준다.

In [44]:
x

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [46]:
x = np.zeros((5,4))

In [47]:
x

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [62]:
x = np.full((5,4),9) #맨뒤는 특정한값을 정해주면 그 값으로 채워준다.

In [64]:
x

array([[9, 9, 9, 9],
       [9, 9, 9, 9],
       [9, 9, 9, 9],
       [9, 9, 9, 9],
       [9, 9, 9, 9]])

---

In [69]:
x = np.ones_like(a)  #a의 shape과 같이 만들어준다.

In [72]:
x

array([[1, 1],
       [1, 1]])

In [56]:
x = np.zeros_like(a)

In [57]:
x

array([[0, 0],
       [0, 0]])

In [59]:
x = np.full_like(a,9)

In [60]:
x

array([[9, 9],
       [9, 9]])

In [65]:
x.strides

(16, 4)

In [74]:
x.astype('float32') #강제로 type을 바꿔준다.

array([[1., 1.],
       [1., 1.]], dtype=float32)

In [80]:
1 / 2

0.5

In [81]:
a = np.array([[1,2],[3,4]])

In [82]:
a.dtype

dtype('int32')

In [78]:
a[0][1] = 1.0

In [79]:
a

array([[1, 1],
       [3, 4]])

In [87]:
a[0][1] ='3'

In [88]:
a

array([[1, 3],
       [3, 4]])

In [89]:
a = np.array([[1,2.0],[3,4]])

In [90]:
a.dtype

dtype('float64')

In [92]:
t = np.array([1,2],dtype='i1')

In [93]:
t

array([1, 2], dtype=int8)